name: dr_nashar_admin
description: admin application for dr nashar

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+7

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  rename: ^2.1.1
  flutter_native_splash: ^2.2.16
  firebase_core: ^2.4.1
  firebase_storage: ^11.0.10
  cloud_firestore: ^4.3.1
  image_picker: ^0.8.7
  video_player: ^2.5.1
  file_picker: ^5.2.5
  shimmer: ^2.0.0
  flutter_spinkit: ^5.1.0
  pdf: ^3.8.4
  path_provider: ^2.0.13
  open_document: ^1.0.6+2
  dependencies:
  excel: ^2.0.4
  liquid_progress_indicator: ^0.4.0
  qr_code_scanner:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.11.0
flutter_native_splash:
  color: "#ffffff"
  image: "images/Icons/appIcon.png"
flutter_icons:
  android: true
  ios: true
  image_path: "images/Icons/appIcon.png"
  remove_alpha_ios: true
  adaptive_icon_foreground: "images/Icons/Icon.png"
  adaptive_icon_background: "#ffffff"


flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/
    - images/Icons/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
