name: Automatic TestFlight Build

on:
  workflow_dispatch:
  schedule:
  - cron: "0 0 */85 * *"

jobs:
  deployment:
    runs-on: ubuntu-latest

    steps:
    - name: Trigger Codemagic Build
      env:
        CODEMAGIC_API_KEY: ${{ secrets.CODEMAGIC_API_KEY }}
        CODEMAGIC_APP_ID: ${{ secrets.CODEMAGIC_APP_ID }}
        CODEMAGIC_WORKFLOW_ID: ${{ secrets.CODEMAGIC_WORKFLOW_ID }}
        DEPLOYMENT_BRANCH: ${{ secrets.DEPLOYMENT_BRANCH }}
      uses: fjogeleit/http-request-action@v1
      with:
        url: 'https://api.codemagic.io/builds'
        method: 'POST'
        customHeaders: '{"Content-Type": "application/json", "X-Auth-Token": "${{ env.CODEMAGIC_API_KEY }}"}'
        data: '{ "appId": "${{ env.CODEMAGIC_APP_ID }}", "workflowId": "${{ env.CODEMAGIC_WORKFLOW_ID }}", "branch": "${{ env.DEPLOYMENT_BRANCH }}" }'